@startuml

title Slet reserveringer

start

:Log ind;
:Klik på min konto;
:Klik på "Reserveringer";
IF (Slet mere end én reservering) then (ja)
:Markér flere reserveringer;
:Klik "Slet markerede reserveringer;
ELSE (nej)
:Klik Slet ud for den reservering der skal slettes;
endif
:Log ud;

stop

@enduml