@startuml
title Shelfmark - Mapping shelfmark from marcXchange
start
if (Does \n 632*m === "SK") then (yes)
  if (Does \n 100 exist?) then (yes)
    :Show first word \n (alfabetised ¤) \n from 100*a;
  else (no)
    if (Does \n 110 exist?) then (yes)
      :Show first word \n (alfabetised ¤) \n from 110*a;
    else (no)
      :Show first word \n (alfabetised ¤) \n from 245*a;
    endif
  endif
else (no)
  if (Does \n 039 exist?) then (yes)
    :Show first word \n (alfabetised ¤) \n from 039*a + *b \n with expansion of coded values;
    if (Does \n 100 exist?) then (yes)
      :Show first word \n (alfabetised ¤) \n from 100*a;
    else (no)
      if (Does \n 110 exist?) then (yes)
        :Show first word \n (alfabetised ¤) \n from 110*a;
      else (no)
        if (Does \n 239 exist?) then (yes)
          :Show first word \n (alfabetised ¤) \n from 239;
        else (no)
          :Show first word \n (alfabetised ¤) \n from 245*a;
        endif
      endif
    endif
  else (no)
    if (Does \n 632*b exist?) then (yes)
      :Show first word \n (alfabetised ¤) \n from 652*m+*b;
    else (no)
      :Show first word \n (alfabetised ¤) \n from 652*m+*h;
      if (Does \n 100 exist?) then (yes)
        :Show first word \n (alfabetised ¤) \n from 100*a;
      else (no)
        if (Does \n 100 exist?) then (yes)
          :Show first word \n (alfabetised ¤) \n from 110*a;
        else (no)
          :Show first word \n (alfabetised ¤) \n from 245*a;
        endif
      endif
    endif
  endif
endif
stop
@enduml