@startuml
Title Docker Containers test med actions

rectangle Containers {
    node mynodea [
        App a
        ====
        bins/libs
    ]

    node mynodeb [
        App b
        ====
        bins/libs
    ]
}

rectangle host {

    node mynodec [
        <b>Containers</b>
        ====
        Docker Engine
        ----
        Host OS
        ....
        Server HW
    ]
}

Containers -[hidden]- host

@endtuml
